Status/urls.py
from django.urls import path
from . import views

app_name = "status"

urlpatterns = [
    path('', views.home_page, name = 'home')
]

Story6/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story6/', include('Status.urls')),
    path('', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story7/urls.py
from django.urls import path
from . import views

app_name = "story7"

urlpatterns = [
    path('', views.story7_page, name = 'story7Page')
]

story8/urls.py
from django.urls import path
from . import views

app_name = "story8"

urlpatterns = [
    path('', views.story8_page, name = 'story8Page'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = "story9"

urlpatterns = [
    path('login/', views.story9_login, name = 'login'),
    path('logout/', views.story9_logout, name = 'logout'),
    path('', views.story9, name= 'home'),
]

Status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    date = models.DateField(auto_now_add=True, null=True)
    time = models.TimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=300)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

Status/forms.py
from django import forms
from . import models

class Status_Form(forms.ModelForm):
    class Meta:
        model = models.Status
        fields = ['status']

Status/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from . forms import Status_Form
from . models import Status
from django.http import HttpResponse

# Create your views here.
def home_page(request):
    if request.method == 'POST':
        form = Status_Form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('status:home')
    else:
        form = Status_Form()
    data = Status.objects.all().order_by('-date', '-time')
    context= {
        'form':form,
        'data':data
    }
    return render(request, "story6.html", context)

story7/views.py
from django.shortcuts import render

# Create your views here.
def story7_page(request):
    return render(request, "story7.html")

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests

# Create your views here.
def story8_page(request):
    return render(request, "story8.html")

story9/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def story9_login(request):
    text = ""
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('story9:home')
        else :
            text = "Enter valid username and password!"
    else :
        if request.user.is_authenticated:
            return redirect('story9:home')
        else:
            form = AuthenticationForm()
    return render(request, 'story9_login.html', {'form':form, 'text':text})

@login_required(login_url='story9:login')
def story9(request):
    return render(request, 'story9.html')

def story9_logout(request):
    logout(request)
    return redirect('story9:login')

templates/story6.html
{% load static %}

<html>
    <head>
        <meta charset = "UTF-8">
        <meta name= "viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'base.css' %}">
        <title>Halo bros</title>
    </head>
    <body>
        <div id="halo">
            <div id="apakabar">
                <p>Halo, apa kabar?</p>
            </div>

            <form class="form" action="{% url 'status:home' %}" method="POST">
                {% csrf_token %}
                <label>Status : </label>
                <textarea name="status" id="statuxText" cols="30" rows="10" placeholder="Max 300 huruf" required=""></textarea>
                <input class="tombol_simpan" type="submit" value="Simpan">
            </form>

            <form class="data" action="{% url 'status:home'%}" method="GET">
                {% for d in data %}
                <div class="dataData">
                    <div class="date">{{d.date}}</div>
                    <div class="time">{{d.time}}</div>
                    <div class="statusData">{{d.status}}</div> 
                </div>
                {% endfor %}
            </form>
        </div>
    </body>
</html>

templates/story7.html
{% load static %}

<html>
    <head>
        <meta charset = "UTF-8">
        <meta name= "viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'story7.css' %}">
        <title>Story 7</title>
    </head>

    <body>
        <div id="container">
            <div id="navigation">
                <p>Darkmode</p>     
                <label class="switch">
                    <input class ="toggle" type="checkbox">
                    <span class="slider"></span>
                </label>
            </div>

            <div id="sambutan">
                <p>Halo! Apa kabar?</p>
            </div>

            <div id="accordion">
                <div name="acc1" class="borderAcc">
                    <h3>Aktivitas</h3>
                </div>
                <div name="cont1" class="accContent">
                    <p>Aktivitas keseharian saya dipenuhi dengan
                        belajar, main game, serta menikmati musik
                        selama perjalanan di kereta. Selain itu sekarang
                        saya sedang aktif dalam Biro Media BEM Fasilkom UI,
                        juga menjadi wali kelas SBF Media. 
                        <br>
                        <br>
                        Selama liburan, aktivitas favorit saya adalah tiduran,
                        scrolling sosmed sampai mata dan jempol sakit sambil
                        mendengarkan musik :(
                    </p>
                </div>
                
                <div name="acc2" class="borderAcc">
                    <h3>Pengalaman</h3>
                </div>
                <div name="cont2" class="accContent">
                    <h4>Organisasi</h4>
                    <ul>- Staff Biro Media BEM Fasilkom UI </ul>
                    <ul>- Staff Departemen Kominfo KMBUI</ul>
                    <ul>- Koordinator Bidang Kesehatan OSIS SMAK2 PENABUR Jakarta </ul>

                    <h4>Kepanitiaan</h4>
                    <ul>- Koordinator English Debate SMAK2 Cup 2017</ul>
                    <ul>- Staff TOEFL Educare 2019</ul>
                    <ul>- Staff Design Waisak KMBUI 2019</ul>
                    <ul>- Staff Software Engineering Academy COMPFEST 11 </ul>
                    <ul>- VPIC of Software Engineering Academy at COMPFEST 12</ul>
                </div>

                <div name="acc3" class="borderAcc">
                    <h3>Prestasi</h3>
                </div>
                <div name="cont3" class="accContent">
                    <ul>- Selama kuliah baru begadang 2 kali</ul>
                    <ul>- Bisa masuk Fasilkom UI UwU</ul>
                    <ul>- Mungkin Juara 1 tukang ngeluh di Quanta</ul>
                </div>
            </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="{% static 'story7.js' %}"></script>
    </body>
</html>

templates/story8.html
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <link rel="stylesheet" href="{% static 'story8.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
        <script src="http://code.jquery.com/jquery-3.4.1.js"></script>
        <script src="{% static 'scriptStory8.js' %}"></script>
        <title>Story 8</title>
    </head>
    <body>
        <h1>BOOK SEARCHER</h1>

        <input id="search" type="text" placeholder ="Search">
        <input type="submit" id="button" value="search">
    
        <table class="table table-dark">
            <thead>
              <tr>
                <th scope="col">No.</th>
                <th scope="col" class="judul">Judul Buku</th>
                <th scope="col" class="deskripsi">Deskripsi Buku</th>
                <th scope="col" class="link">Penulis Buku</th>
                <th scope="col" class="gambar">Gambar Buku</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </body>
</html>

templates/story9.html
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <link rel="stylesheet" href="{% static 'story9.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
        <title>Story 9</title>
    </head>
    <body>
        <div id="sambut">
            <h1>Hai! {{ user.first_name }}</h1>
            <a href="{% url 'story9:logout' %}" class="logoutButton">
                logout
            </a>
        </div>
    </body>
</html>

templates/story9_login.html
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <link rel="stylesheet" href="{% static 'story9.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
        <title>Story 9 Login Page</title>
    </head>
    <body>
        <form action="{% url 'story9:login' %}" method = "POST">
            <div id="loginForm">
                {% csrf_token %}
                <label for="id_username" id="user_label">Username : </label>
                <input type="text" name="username" autofocus="" required="" id="id_username">
                <label for="id_password" id="pass_label">Password : </label>
                <input type="password" name="password" required="" id="id_password">
                <input class="button" type="submit" value="Login">
            </div>

            <p id="warning">{{ text }}</p>
        </form>

        <div id="testerID">
            <p>Login username = test</p>
            <p>Login password = tester12</p>
        </div>
    </body>
</html>